// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------------- //
// pulse_generator //
// --------------- //

#define pulse_generator_wrap_target 0
#define pulse_generator_wrap 6
#define pulse_generator_pio_version 0

static const uint16_t pulse_generator_program_instructions[] = {
            //     .wrap_target
    0x90a0, //  0: pull   block           side 0
    0x6020, //  1: out    x, 32
    0x7801, //  2: out    pins, 1         side 1
    0x6001, //  3: out    pins, 1
    0x0043, //  4: jmp    x--, 3
    0xa00b, //  5: mov    pins, ~null
    0xd020, //  6: irq    wait 0          side 0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program pulse_generator_program = {
    .instructions = pulse_generator_program_instructions,
    .length = 7,
    .origin = -1,
    .pio_version = pulse_generator_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config pulse_generator_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + pulse_generator_wrap_target, offset + pulse_generator_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif

