#include <Arduino.h>
#include <hardware/pio.h>
#include "quad_spi.pio.h" // Automatically generated by PlatformIO during compilation

// Display Configuration
const int NUM_CHANNELS  = 4;   // 4 Text Lines (one per channel)
const int MATRIX_ROWS   = 7;   // 7 multiplexed rows per character
const int MATRIX_COLS   = 240; // 240 horizontal columns wide
const int CHAR_WIDTH    = 5;   // Width of one character in pixels
const int CHAR_SPACING  = 1;   // Blank pixel columns between letters

// Pin Allocation
const int SHARED_CLK_PIN = 2;
const int BASE_DATA_PIN  = 3;  // Uses GPIO 3, 4, 5, 6 for Channel 1, 2, 3, 4
const int LATCH_PIN      = 14; // Shift register strobe/latch pulse
const int ENABLE_PIN     = 15; // Shift register common output enable
const int ROW_PINS[MATRIX_ROWS] = {7, 8, 9, 10, 11, 12, 13}; // Common row switches

// Logical Frame Buffer: [Channel][Row][Column]
uint8_t text_matrix[NUM_CHANNELS][MATRIX_ROWS][MATRIX_COLS];

PIO pio = pio0;
uint sm = 0;

// Functions declarations for C++ strict compilation
void print_line(int channel, const char* text);
void scan_and_render_display();

// Basic Alphanumeric Font Map (0-9, A-Z)
// 5 bytes per character. Bit 0 = Top row, Bit 6 = Bottom row.
const uint8_t alpha_font[36][5] PROGMEM = {
  // Numbers 0 - 9 (Indices 0 to 9)
  { 0x3E, 0x51, 0x49, 0x45, 0x3E }, // '0'
  { 0x00, 0x42, 0x7F, 0x40, 0x00 }, // '1'
  { 0x42, 0x61, 0x51, 0x49, 0x46 }, // '2'
  { 0x22, 0x41, 0x49, 0x49, 0x36 }, // '3'
  { 0x18, 0x14, 0x12, 0x7F, 0x10 }, // '4'
  { 0x27, 0x45, 0x45, 0x45, 0x39 }, // '5'
  { 0x3C, 0x4A, 0x49, 0x49, 0x30 }, // '6'
  { 0x01, 0x71, 0x09, 0x05, 0x03 }, // '7'
  { 0x36, 0x49, 0x49, 0x49, 0x36 }, // '8'
  { 0x06, 0x49, 0x49, 0x29, 0x1E }, // '9'

  // Letters A - Z (Indices 10 to 35)
  { 0x7E, 0x11, 0x11, 0x11, 0x7E }, // 'A'
  { 0x7F, 0x49, 0x49, 0x49, 0x36 }, // 'B'
  { 0x3E, 0x41, 0x41, 0x41, 0x22 }, // 'C'
  { 0x7F, 0x41, 0x41, 0x22, 0x1C }, // 'D'
  { 0x7F, 0x49, 0x49, 0x49, 0x41 }, // 'E'
  { 0x7F, 0x09, 0x09, 0x09, 0x01 }, // 'F'
  { 0x3E, 0x41, 0x49, 0x49, 0x7A }, // 'G'
  { 0x7F, 0x08, 0x08, 0x08, 0x7F }, // 'H'
  { 0x00, 0x41, 0x7F, 0x41, 0x00 }, // 'I'
  { 0x20, 0x40, 0x41, 0x3F, 0x01 }, // 'J'
  { 0x7F, 0x08, 0x14, 0x22, 0x41 }, // 'K'
  { 0x7F, 0x40, 0x40, 0x40, 0x40 }, // 'L'
  { 0x7F, 0x02, 0x0C, 0x02, 0x7F }, // 'M'
  { 0x7F, 0x04, 0x08, 0x10, 0x7F }, // 'N'
  { 0x3E, 0x41, 0x41, 0x41, 0x3E }, // 'O'
  { 0x7F, 0x09, 0x09, 0x09, 0x06 }, // 'P'
  { 0x3E, 0x41, 0x51, 0x21, 0x5E }, // 'Q'
  { 0x7F, 0x09, 0x19, 0x29, 0x46 }, // 'R'
  { 0x46, 0x49, 0x49, 0x49, 0x31 }, // 'S'
  { 0x01, 0x01, 0x7F, 0x01, 0x01 }, // 'T'
  { 0x3F, 0x40, 0x40, 0x40, 0x3F }, // 'U'
  { 0x1F, 0x20, 0x40, 0x20, 0x1F }, // 'V'
  { 0x3F, 0x40, 0x38, 0x40, 0x3F }, // 'W'
  { 0x63, 0x14, 0x08, 0x14, 0x63 }, // 'X'
  { 0x07, 0x08, 0x70, 0x08, 0x07 }, // 'Y'
  { 0x61, 0x51, 0x49, 0x45, 0x43 }  // 'Z'
};

// Translates basic text into the logical matrix
void print_line(int channel, const char* text) {
  if (channel < 0 || channel >= NUM_CHANNELS) return;

  // Clear previous pixel data for this specific channel line
  for (int r = 0; r < MATRIX_ROWS; r++) {
    for (int c = 0; c < MATRIX_COLS; c++) {
      text_matrix[channel][r][c] = 0;
    }
  }

  int col_cursor = 0;
  for (int i = 0; text[i] != '\0'; i++) {
    char c = text[i];
    int font_idx = -1;

    // Convert char to font index map
    if (c >= '0' && c <= '9') {
      font_idx = c - '0';
    } else if (c >= 'A' && c <= 'Z') {
      font_idx = c - 'A' + 10;
    } else if (c >= 'a' && c <= 'z') {
      font_idx = c - 'a' + 10; // Auto-map lowercase to uppercase
    }

    // If character is a space or invalid, skip space ahead
    if (font_idx == -1) {
      col_cursor += CHAR_WIDTH + CHAR_SPACING;
      continue;
    }

    // Copy character columns into layout matrix
    for (int col = 0; col < CHAR_WIDTH; col++) {
      if (col_cursor >= MATRIX_COLS) break;
      
      // Fetch column bitmask byte from Flash memory
      uint8_t column_data = pgm_read_byte(&(alpha_font[font_idx][col]));
      
      for (int row = 0; row < MATRIX_ROWS; row++) {
        if ((column_data >> ((MATRIX_ROWS-1)-row)) & 1) { // inverted font top to bottom
          text_matrix[channel][row][col_cursor] = 1;
        }
      }
      col_cursor++;
    }
    col_cursor += CHAR_SPACING; // Append spacing after character
  }
}

void setup() {
  // Initialize PIO 4-channel driver using state machine 0
  uint offset = pio_add_program(pio, &quad_spi_program);
  pio_sm_config c = quad_spi_program_get_default_config(offset);
  
  sm_config_set_out_pins(&c, BASE_DATA_PIN, NUM_CHANNELS);
  for(int i = 0; i < NUM_CHANNELS; i++) pio_gpio_init(pio, BASE_DATA_PIN + i);
  pio_sm_set_consecutive_pindirs(pio, sm, BASE_DATA_PIN, NUM_CHANNELS, true);

  sm_config_set_sideset_pins(&c, SHARED_CLK_PIN);
  pio_gpio_init(pio, SHARED_CLK_PIN);
  pio_sm_set_consecutive_pindirs(pio, sm, SHARED_CLK_PIN, 1, true);

  sm_config_set_out_shift(&c, true, true, 32);
  sm_config_set_clkdiv(&c, 12.5f); // Clock configured to ~10 MHz
  pio_sm_init(pio, sm, offset, &c);
  pio_sm_set_enabled(pio, sm, true);

  // Initialize Shift Register Strobe Latch & Multiplex Row selectors
  pinMode(LATCH_PIN, OUTPUT);
  digitalWrite(LATCH_PIN, LOW);

  pinMode(ENABLE_PIN, OUTPUT);
  digitalWrite(ENABLE_PIN, LOW);

  for (int i = 0; i < MATRIX_ROWS; i++) {
    pinMode(ROW_PINS[i], OUTPUT);
    digitalWrite(ROW_PINS[i], LOW);
  }

  // Load custom strings into each independent text line
  print_line(0, "PLATFORMIO ACTIVE RUNNING");
  print_line(1, "RP2040 QUAD PIO DRIVER");
  print_line(2, "AUTO PIO COMPILATION OK");
  print_line(3, "ABC 123 TEST DISPLAY OK");
}

void loop() {
  scan_and_render_display(); // Continuous display refresh matrix sweep
}

// Drives 240 bits per channel per row, then toggles common rows
void scan_and_render_display() {
  for (int row = 0; row < MATRIX_ROWS; row++) {
    
    uint32_t bit_accumulator = 0;
    int packed_slices = 0;

    // Stream 240 columns sequentially for this row phase
    for (int col = 0; col < MATRIX_COLS; col++) {
      
    // If the image is mirrored, reverse the index order:
    int target_col = (MATRIX_COLS - 1) - col; 

    // Pull bits from all 4 channels at this specific coordinate
      uint32_t slice = 0;
      slice |= (!text_matrix[0][row][target_col]) << 0;
      slice |= (!text_matrix[1][row][target_col]) << 1;
      slice |= (!text_matrix[2][row][target_col]) << 2;
      slice |= (!text_matrix[3][row][target_col]) << 3;

      // Pack 4 bits into current 32-bit hardware register slot
      bit_accumulator |= (slice << (packed_slices * 4));
      packed_slices++;

      // When register is full (8 slices * 4 bits = 32 bits), send to PIO FIFO
      if (packed_slices == 8) {
        pio_sm_put_blocking(pio, sm, bit_accumulator);
        bit_accumulator = 0;
        packed_slices = 0;
      }
    }

    // Flush remaining residual bits to hardware
    if (packed_slices > 0) {
      pio_sm_put_blocking(pio, sm, bit_accumulator);
    }

    // --- LATCH AND MUTEX DISPLAY REFRESH STEP ---
    // 1. Turn off row drivers to clear the display (Prevents ghosting)
    for (int i = 0; i < MATRIX_ROWS; i++) {
      digitalWrite(ROW_PINS[i], LOW);
    }

    // 2. Pulse Latch pin HIGH to lock data into column drivers
    digitalWrite(LATCH_PIN, HIGH);
    delayMicroseconds(2);
    digitalWrite(LATCH_PIN, LOW);

    delayMicroseconds(1000); // limit brightness by holding off fot a bit
  // 3. Switch on current row driver line
    digitalWrite(ROW_PINS[row], HIGH);

    // 4. Hold active frame on display matrix for 1.5 milliseconds
    delayMicroseconds(500); 
  }
}
