// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// -------- //
// quad_spi //
// -------- //

#define quad_spi_wrap_target 0
#define quad_spi_wrap 1
#define quad_spi_pio_version 0

static const uint16_t quad_spi_program_instructions[] = {
            //     .wrap_target
    0x6004, //  0: out    pins, 4         side 0
    0xb042, //  1: nop                    side 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program quad_spi_program = {
    .instructions = quad_spi_program_instructions,
    .length = 2,
    .origin = -1,
    .pio_version = quad_spi_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config quad_spi_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + quad_spi_wrap_target, offset + quad_spi_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}
#endif

