#include <Arduino.h>
#include <hardware/pio.h>
#include "quad_spi.pio.h" // Automatically generated by PlatformIO during compilation
#include "config.h"
#if 0
#include "matrix_pulse_manager.h"
#endif

// Display Configuration
const int NUM_CHANNELS  = 4;   // 4 Text Lines (one per channel)
const int MATRIX_ROWS   = 7;   // 7 multiplexed rows per character
const int MATRIX_COLS   = 180; // 180 horizontal columns wide
const int CHAR_WIDTH    = 5;   // Width of one character in pixels
const int CHAR_SPACING  = 1;   // Blank pixel columns between letters

// Pin Allocation
const int SHARED_CLK_PIN = 2;
const int BASE_DATA_PIN  = 3;  // Uses GPIO 3, 4, 5, 6 for Channel 1, 2, 3, 4
const int LATCH_PIN      = 14; // Shift register strobe/latch pulse
#if 1
const int ENABLE_PIN     = 15; // Shift register common output enable
#else
const int ENABLE_PIN     = 28; // Shift register common output enable
#endif
const int ROW_PINS[MATRIX_ROWS] = {7, 8, 9, 10, 11, 12, 13}; // Common row switches

// Logical Frame Buffer: [Channel][Row][Column]
volatile uint8_t text_matrix[NUM_CHANNELS][MATRIX_ROWS][MATRIX_COLS];
extern const uint8_t alpha_font[96][5];

PIO pio = pio0;
uint sm = 0;

// Functions declarations for C++ strict compilation
void print_line(int channel, const char* text);
void scan_and_render_display(int ledBrightnes);

// Translates basic text into the logical matrix
void print_line(int logical_channel, const char* text) {

  if (logical_channel < 0 || logical_channel >= NUM_CHANNELS) return;

  // REMAP CHANNELS FOR 180° ROTATION:
  int channel = (NUM_CHANNELS - 1) - logical_channel;

  // Clear previous pixel data for this specific channel line
  for (int r = 0; r < MATRIX_ROWS; r++) {
    for (int c = 0; c < MATRIX_COLS; c++) {
      text_matrix[channel][r][c] = 0;
    }
  }

  int col_cursor = 0;
  for (int i = 0; text[i] != '\0'; i++) {
    char c = text[i];
    int font_idx = -1;

    if(c > 32 && c <= 127)
      font_idx =(uint8_t)(c - 32);

    // If character is a space or invalid, skip space ahead
    if (font_idx == -1) {
      col_cursor += CHAR_WIDTH + CHAR_SPACING;
      continue;
    }

    // Copy character columns into layout matrix
    for (int col = 0; col < CHAR_WIDTH; col++) {
      if (col_cursor >= MATRIX_COLS) break;
      
      // Fetch column bitmask byte from Flash memory
      uint8_t column_data = pgm_read_byte(&(alpha_font[font_idx][col]));
      
      for (int row = 0; row < MATRIX_ROWS; row++) {
        if ((column_data >> row) & 1) { // non inverted font
          text_matrix[channel][row][col_cursor] = 1;
        }
      }
      col_cursor++;
    }
    col_cursor += CHAR_SPACING; // Append spacing after character
  }
}

#if 0
void led_display_cont(bool enable){
  if(enable)
      digitalWrite(ENABLE_PIN, LOW);
    else 
      digitalWrite(ENABLE_PIN, HIGH);
}
#endif

void setup1() {

  // Initialize Shift Register Strobe Latch & Multiplex Row selectors
  pinMode(LATCH_PIN, OUTPUT);
  digitalWriteFast(LATCH_PIN, LOW);

  pinMode(ENABLE_PIN, OUTPUT);
  digitalWriteFast(ENABLE_PIN, HIGH); //disable

  for (int i = 0; i < MATRIX_ROWS; i++) {
    pinMode(ROW_PINS[i], OUTPUT);
    digitalWriteFast(ROW_PINS[i], LOW);
  }

  Serial.println("led_setup...");

#if 0
  while (!pulseManager.is_hardware_ready()) {
      __compiler_memory_barrier();
  }
#endif

  // Initialize PIO 4-channel driver using state machine 0
  uint offset = pio_add_program(pio, &quad_spi_program);
  pio_sm_config c = quad_spi_program_get_default_config(offset);
  
  sm_config_set_out_pins(&c, BASE_DATA_PIN, NUM_CHANNELS);
  for(int i = 0; i < NUM_CHANNELS; i++) pio_gpio_init(pio, BASE_DATA_PIN + i);
  pio_sm_set_consecutive_pindirs(pio, sm, BASE_DATA_PIN, NUM_CHANNELS, true);

  sm_config_set_sideset_pins(&c, SHARED_CLK_PIN);
  pio_gpio_init(pio, SHARED_CLK_PIN);
  pio_sm_set_consecutive_pindirs(pio, sm, SHARED_CLK_PIN, 1, true);

  sm_config_set_out_shift(&c, true, true, 32);
  sm_config_set_clkdiv(&c, 12.5f); // Clock configured to ~10 MHz
  pio_sm_init(pio, sm, offset, &c);
  pio_sm_set_enabled(pio, sm, true);

  // Load custom strings into each independent text line
  tone(BELL_PIN, 2500, 200); 
  #if 0
  print_line(0, "0");
  print_line(1, "1");
  print_line(2, "2");
  print_line(3, "3");
  scan_and_render_display(0); // Continuous display refresh matrix sweep
  #endif
 
}

// Drive 180 bits per channel per row, then toggles common rows
void scan_and_render_display(int ledBrightnes) {
  int  brightness = ledBrightnes * 20; // = on time, off for 2000-brightness uS
    // 1. Inverted Vertical Scan (Row 6 down to 0)
  for (int row = MATRIX_ROWS - 1; row >= 0; row--) {
    
    uint32_t bit_accumulator = 0;
    int packed_slices = 0;

    // --- STEP A: PUSH 4 DUMMY CLOCK PADS FIRST ---
    // Because 180 cols is 4 cols short of a 32-bit chunk (23 words * 8 slices = 184 cols),
    // we send 4 blank dummy slices at the beginning of the row.
    // Inverted Display Rule: 0b1111 represents "all channels dark"
    for (int pad = 0; pad < 4; pad++) {
      uint32_t blank_slice = 0x0F; 
      bit_accumulator |= (blank_slice << (packed_slices * 4));
      packed_slices++;
    }

    // --- STEP B: STREAM YOUR LOGICAL DATA (179 down to 0) ---
    for (int col = 0; col < MATRIX_COLS ; col++) {
      
      uint32_t slice = 0;
      slice |= (text_matrix[0][row][col] & 1) << 0; // Layer 0 -> Pin 3
      slice |= (text_matrix[1][row][col] & 1) << 1; // Layer 1 -> Pin 4
      slice |= (text_matrix[2][row][col] & 1) << 2; // Layer 2 -> Pin 5
      slice |= (text_matrix[3][row][col] & 1) << 3; // Layer 3 -> Pin 6

      // Pixel Inversion (Masked to lowest 4 bits)
      slice = (~slice) & 0x0F;

      bit_accumulator |= (slice << (packed_slices * 4));
      packed_slices++;

      // Every 8 slices (32 bits complete), push straight to hardware
      if (packed_slices == 8) {
        pio_sm_put_blocking(pio, sm, bit_accumulator);
        bit_accumulator = 0;
        packed_slices = 0;
      }
    }

    // NOTE: Because (4 pads + 180 cols) = 184 cols, which is exactly 23 words,
    // packed_slices will ALWAYS equal 0 here. No trailing flush block is required!

    // --- LATCH AND MUTEX DISPLAY REFRESH STEP ---
    // 1. Turn off row drivers to clear the display (Prevents ghosting)
    for (int i = 0; i < MATRIX_ROWS; i++) {
      digitalWriteFast(ROW_PINS[i], LOW);
    }
    delayMicroseconds(1);

    // 2. Pulse Latch pin HIGH to lock data into column drivers
    digitalWriteFast(LATCH_PIN, HIGH);
    delayMicroseconds(1);
    digitalWriteFast(LATCH_PIN, LOW);

  // 3. Switch on current row driver line
    digitalWriteFast(ROW_PINS[row], HIGH);

#if 1
    delayMicroseconds(2000-brightness);
 // light the display
    digitalWriteFast(ENABLE_PIN, LOW); // display on
    delayMicroseconds(brightness);
    digitalWriteFast(ENABLE_PIN, HIGH); // display off
#else
    pulseManager.fire_blocking_pulse(); 
#endif
    for (int i = 0; i < MATRIX_ROWS; i++) {
      digitalWriteFast(ROW_PINS[i], LOW);
    }

   }
}


void loop1() {
  scan_and_render_display(led_brightness);
 }
