#include <Arduino.h>
#include <hardware/pio.h>
#include "quad_spi.pio.h" // Automatically generated by PlatformIO during compilation
#include "config.h"

// Display Configuration
const int NUM_CHANNELS  = 4;   // 4 Text Lines (one per channel)
const int MATRIX_ROWS   = 7;   // 7 multiplexed rows per character
const int MATRIX_COLS   = 180; // 180 horizontal columns wide
const int CHAR_WIDTH    = 5;   // Width of one character in pixels
const int CHAR_SPACING  = 1;   // Blank pixel columns between letters

// Pin Allocation
const int SHARED_CLK_PIN = 2;
const int BASE_DATA_PIN  = 3;  // Uses GPIO 3, 4, 5, 6 for Channel 1, 2, 3, 4
const int LATCH_PIN      = 14; // Shift register strobe/latch pulse
const int ENABLE_PIN     = 15; // Shift register common output enable
const int ROW_PINS[MATRIX_ROWS] = {7, 8, 9, 10, 11, 12, 13}; // Common row switches

// Logical Frame Buffer: [Channel][Row][Column]
volatile uint8_t text_matrix[NUM_CHANNELS][MATRIX_ROWS][MATRIX_COLS];

PIO pio = pio0;
uint sm = 0;

// Functions declarations for C++ strict compilation
void print_line(int channel, const char* text);
void scan_and_render_display(int ledBrightnes);

// Full 5x7 ASCII Font Map (ASCII 32 to 122)
// 91 characters total. Bit 0 = Top row, Bit 6 = Bottom row.
const uint8_t alpha_font[96][6] PROGMEM = {
  { 0x00, 0x00, 0x00, 0x00, 0x00 }, // 32: Space
  { 0x00, 0x00, 0x5F, 0x00, 0x00 }, // 33: !
  { 0x00, 0x03, 0x00, 0x03, 0x00 }, // 34: "
  { 0x14, 0x7F, 0x14, 0x7F, 0x14 }, // 35: #
  { 0x24, 0x2A, 0x7F, 0x2A, 0x12 }, // 36: $
  { 0x23, 0x13, 0x08, 0x64, 0x62 }, // 37: %
  { 0x36, 0x49, 0x55, 0x22, 0x50 }, // 38: &
  { 0x00, 0x05, 0x03, 0x00, 0x00 }, // 39: '
  { 0x00, 0x1C, 0x22, 0x41, 0x00 }, // 40: (
  { 0x00, 0x41, 0x22, 0x1C, 0x00 }, // 41: )
  { 0x08, 0x2A, 0x1C, 0x2A, 0x08 }, // 42: *
  { 0x08, 0x08, 0x3E, 0x08, 0x08 }, // 43: +
  { 0x00, 0x50, 0x30, 0x00, 0x00 }, // 44: ,
  { 0x08, 0x08, 0x08, 0x08, 0x08 }, // 45: -
  { 0x00, 0x60, 0x60, 0x00, 0x00 }, // 46: .
  { 0x20, 0x10, 0x08, 0x04, 0x02 }, // 47: /
  
  // Numbers 0 - 9 (ASCII 48 to 57)
  { 0x3E, 0x51, 0x49, 0x45, 0x3E }, // 48: 0
  { 0x00, 0x42, 0x7F, 0x40, 0x00 }, // 49: 1
  { 0x42, 0x61, 0x51, 0x49, 0x46 }, // 50: 2
  { 0x22, 0x41, 0x49, 0x49, 0x36 }, // 51: 3
  { 0x18, 0x14, 0x12, 0x7F, 0x10 }, // 52: 4
  { 0x27, 0x45, 0x45, 0x45, 0x39 }, // 53: 5
  { 0x3C, 0x4A, 0x49, 0x49, 0x30 }, // 54: 6
  { 0x01, 0x71, 0x09, 0x05, 0x03 }, // 55: 7
  { 0x36, 0x49, 0x49, 0x49, 0x36 }, // 56: 8
  { 0x06, 0x49, 0x49, 0x29, 0x1E }, // 57: 9
  
  { 0x00, 0x00, 0x36, 0x36, 0x00 }, // 58: :
  { 0x00, 0x56, 0x36, 0x00, 0x00 }, // 59: ; (Semicolon - 2-dot wide top section)
  { 0x08, 0x14, 0x22, 0x41, 0x00 }, // 60: <
  { 0x14, 0x14, 0x14, 0x14, 0x14 }, // 61: =
  { 0x00, 0x41, 0x22, 0x14, 0x08 }, // 62: >
  { 0x02, 0x01, 0x51, 0x09, 0x06 }, // 63: ?
  { 0x32, 0x49, 0x79, 0x41, 0x3E }, // 64: @
  
  // Uppercase Letters A - Z (ASCII 65 to 90)
  { 0x7E, 0x11, 0x11, 0x11, 0x7E, 0 }, // 65: A
  { 0x7F, 0x49, 0x49, 0x49, 0x36, 0 }, // 66: B
  { 0x3E, 0x41, 0x41, 0x41, 0x22, 0 }, // 67: C
  { 0x7F, 0x41, 0x41, 0x22, 0x1C }, // 68: D
  { 0x7F, 0x49, 0x49, 0x49, 0x41 }, // 69: E
  { 0x7F, 0x09, 0x09, 0x09, 0x01 }, // 70: F
  { 0x3E, 0x41, 0x49, 0x49, 0x7A }, // 71: G
  { 0x7F, 0x08, 0x08, 0x08, 0x7F }, // 72: H
  { 0x00, 0x41, 0x7F, 0x41, 0x00 }, // 73: I
  { 0x20, 0x40, 0x41, 0x3F, 0x01 }, // 74: J
  { 0x7F, 0x08, 0x14, 0x22, 0x41 }, // 75: K
  { 0x7F, 0x40, 0x40, 0x40, 0x40 }, // 76: L
  { 0x7F, 0x02, 0x0C, 0x02, 0x7F }, // 77: M
  { 0x7F, 0x04, 0x08, 0x10, 0x7F }, // 78: N
  { 0x3E, 0x41, 0x41, 0x41, 0x3E }, // 79: O
  { 0x7F, 0x09, 0x09, 0x09, 0x06 }, // 80: P
  { 0x3E, 0x41, 0x51, 0x21, 0x5E }, // 81: Q
  { 0x7F, 0x09, 0x19, 0x29, 0x46 }, // 82: R
  { 0x46, 0x49, 0x49, 0x49, 0x31 }, // 83: S
  { 0x01, 0x01, 0x7F, 0x01, 0x01 }, // 84: T
  { 0x3F, 0x40, 0x40, 0x40, 0x3F }, // 85: U
  { 0x1F, 0x20, 0x40, 0x20, 0x1F }, // 86: V
  { 0x3F, 0x40, 0x38, 0x40, 0x3F }, // 87: W
  { 0x63, 0x14, 0x08, 0x14, 0x63 }, // 88: X
  { 0x07, 0x08, 0x70, 0x08, 0x07 }, // 89: Y
  { 0x61, 0x51, 0x49, 0x45, 0x43 }, // 90: Z
  
  { 0x00, 0x7F, 0x41, 0x41, 0x00 }, // 91: [
  { 0x02, 0x04, 0x08, 0x10, 0x20 }, // 92: '\'
  { 0x00, 0x41, 0x41, 0x7F, 0x00 }, // 93: ]
  { 0x04, 0x02, 0x01, 0x02, 0x04 }, // 94: ^
  { 0x40, 0x40, 0x40, 0x40, 0x40 }, // 95: _
  { 0x00, 0x01, 0x02, 0x00, 0x00 }, // 96: `

 // Lowercase Letters a - z (ASCII 97 to 122)
  { 0x20, 0x54, 0x54, 0x54, 0x78 }, // 97: a
  { 0x7F, 0x48, 0x44, 0x44, 0x38 }, // 98: b
  { 0x38, 0x44, 0x44, 0x44, 0x20 }, // 99: c
  { 0x38, 0x44, 0x44, 0x48, 0x7F }, // 100: d
  { 0x38, 0x54, 0x54, 0x54, 0x18 }, // 101: e
  { 0x08, 0x7E, 0x09, 0x01, 0x02 }, // 102: f
  { 0x0C, 0x52, 0x52, 0x52, 0x3E }, // 103: g
  { 0x7F, 0x08, 0x04, 0x04, 0x78 }, // 104: h
  { 0x00, 0x44, 0x7D, 0x40, 0x00 }, // 105: i
  { 0x20, 0x40, 0x44, 0x3D, 0x00 }, // 106: j
  { 0x7F, 0x10, 0x28, 0x44, 0x00 }, // 107: k
  { 0x00, 0x41, 0x7F, 0x40, 0x00 }, // 108: l
  { 0x7C, 0x04, 0x18, 0x04, 0x78 }, // 109: m
  { 0x7C, 0x08, 0x04, 0x04, 0x78 }, // 110: n
  { 0x38, 0x44, 0x44, 0x44, 0x38 }, // 111: o
  { 0x7C, 0x14, 0x14, 0x14, 0x08 }, // 112: p
  { 0x08, 0x14, 0x14, 0x14, 0x7C }, // 113: q
  { 0x7C, 0x08, 0x04, 0x04, 0x08 }, // 114: r
  { 0x48, 0x54, 0x54, 0x54, 0x20 }, // 115: s
  { 0x04, 0x3F, 0x44, 0x40, 0x20 }, // 116: t
  { 0x3C, 0x40, 0x40, 0x20, 0x7C }, // 117: u
  { 0x1C, 0x20, 0x40, 0x20, 0x1C }, // 118: v
  { 0x3C, 0x40, 0x30, 0x40, 0x3C }, // 119: w
  { 0x44, 0x28, 0x10, 0x28, 0x44 }, // 120: x
  { 0x0C, 0x50, 0x50, 0x50, 0x3c }, // 121: y
  { 0x44, 0x64, 0x54, 0x4C, 0x44 }, // 122: z

  { 0x00, 0x08, 0x36, 0x41, 0x00 }, // 123: {
  { 0x00, 0x00, 0x7F, 0x00, 0x00 }, // 124: |
  { 0x00, 0x41, 0x36, 0x08, 0x00 }, // 125: }
  { 0x04, 0x02, 0x04, 0x08, 0x04 }  // 126: ~
};

// 12 Custom Characters rotated into Column-Major Format (6 Bytes per Character)
// Byte 0 = Leftmost column, Byte 5 = Rightmost spacer column.
// Inside each byte: Bit 0 = Top row (Mux 0), Bit 6 = Bottom row (Mux 6).

const uint8_t qr_font_rotated[12][6] = {
  // === LINE 0 (QR Rows 0 to 6) ===
  { 0x7F, 0x41, 0x5D, 0x5D, 0x41, 0x7F }, // Char 0 (Cols 0-5)
  { 0x22, 0x1E, 0x55, 0x72, 0x4B, 0x2C }, // Char 1 (Cols 6-11)
  { 0x3E, 0x7F, 0x05, 0x63, 0x16, 0x4E }, // Char 2 (Cols 12-17)
  { 0x7F, 0x41, 0x5D, 0x5D, 0x41, 0x7F }, // Char 3 (Cols 18-23, incorporates right border)

  // === LINE 1 (QR Rows 7 to 13) ===
  { 0x3C, 0x27, 0x5D, 0x11, 0x45, 0x38 }, // Char 4
  { 0x1A, 0x7E, 0x23, 0x57, 0x64, 0x0C }, // Char 5
  { 0x53, 0x2E, 0x7C, 0x18, 0x45, 0x31 }, // Char 6
  { 0x42, 0x36, 0x78, 0x0F, 0x51, 0x2D }, // Char 7

  // === LINE 2 (QR Rows 14 to 20) ===
  { 0x7F, 0x41, 0x5D, 0x5D, 0x41, 0x7F }, // Char 8
  { 0x2B, 0x64, 0x1E, 0x73, 0x55, 0x02 }, // Char 9
  { 0x7A, 0x07, 0x5D, 0x3C, 0x6E, 0x1F }, // Char 10
  { 0x47, 0x3F, 0x10, 0x6A, 0x25, 0x5E }  // Char 11
};


// Translates basic text into the logical matrix
void print_line(int logical_channel, const char* text) {

  if (logical_channel < 0 || logical_channel >= NUM_CHANNELS) return;

  // REMAP CHANNELS FOR 180° ROTATION:
  int channel = (NUM_CHANNELS - 1) - logical_channel;

  // Clear previous pixel data for this specific channel line
  for (int r = 0; r < MATRIX_ROWS; r++) {
    for (int c = 0; c < MATRIX_COLS; c++) {
      text_matrix[channel][r][c] = 0;
    }
  }

  int col_cursor = 0;
  for (int i = 0; text[i] != '\0'; i++) {
    char c = text[i];
    int font_idx = -1;

    if(c > 32 && c <= 127)
      font_idx =(uint8_t)(c - 32);

    // If character is a space or invalid, skip space ahead
    if (font_idx == -1) {
      col_cursor += CHAR_WIDTH + CHAR_SPACING;
      continue;
    }

    // Copy character columns into layout matrix
    for (int col = 0; col <= CHAR_WIDTH; col++) {
      if (col_cursor >= MATRIX_COLS) break;
      
      // Fetch column bitmask byte from Flash memory
      uint8_t column_data = pgm_read_byte(&(alpha_font[font_idx][col]));
      
      for (int row = 0; row < MATRIX_ROWS; row++) {
        if ((column_data >> row) & 1) { // non inverted font
          text_matrix[channel][row][col_cursor] = 1;
        }
      }
      col_cursor++;
    }
    //col_cursor += CHAR_SPACING; // Append spacing after character
  }
}

void led_display_cont(bool enable){
  if(enable)
      digitalWrite(ENABLE_PIN, LOW);
    else 
      digitalWrite(ENABLE_PIN, HIGH);
}

void setup1() {
  Serial.println("led_setup...");
  // Initialize PIO 4-channel driver using state machine 0
  uint offset = pio_add_program(pio, &quad_spi_program);
  pio_sm_config c = quad_spi_program_get_default_config(offset);
  
  sm_config_set_out_pins(&c, BASE_DATA_PIN, NUM_CHANNELS);
  for(int i = 0; i < NUM_CHANNELS; i++) pio_gpio_init(pio, BASE_DATA_PIN + i);
  pio_sm_set_consecutive_pindirs(pio, sm, BASE_DATA_PIN, NUM_CHANNELS, true);

  sm_config_set_sideset_pins(&c, SHARED_CLK_PIN);
  pio_gpio_init(pio, SHARED_CLK_PIN);
  pio_sm_set_consecutive_pindirs(pio, sm, SHARED_CLK_PIN, 1, true);

  sm_config_set_out_shift(&c, true, true, 32);
  sm_config_set_clkdiv(&c, 12.5f); // Clock configured to ~10 MHz
  pio_sm_init(pio, sm, offset, &c);
  pio_sm_set_enabled(pio, sm, true);

  // Initialize Shift Register Strobe Latch & Multiplex Row selectors
  pinMode(LATCH_PIN, OUTPUT);
  digitalWrite(LATCH_PIN, LOW);

  pinMode(ENABLE_PIN, OUTPUT);
  digitalWrite(ENABLE_PIN, HIGH); //disable

  for (int i = 0; i < MATRIX_ROWS; i++) {
    pinMode(ROW_PINS[i], OUTPUT);
    digitalWrite(ROW_PINS[i], LOW);
  }

  // Load custom strings into each independent text line
  #if 1
  print_line(0, "0");//The Quick");
  print_line(1, "1");//Brown Fox");
  print_line(2, "2");//Jumps Over");
  print_line(3, "3");//THe Lazy Dog");
  #endif
  tone(BELL_PIN, 2500, 200); 
  scan_and_render_display(0); // Continuous display refresh matrix sweep

}

// Drive 180 bits per channel per row, then toggles common rows
void scan_and_render_display(int ledBrightnes) {
  int  brightness = ledBrightnes * 20; // = on time, off for 2000-brightness uS
    // 1. Inverted Vertical Scan (Row 6 down to 0)
  for (int row = MATRIX_ROWS - 1; row >= 0; row--) {
    
    uint32_t bit_accumulator = 0;
    int packed_slices = 0;

    // --- STEP A: PUSH 4 DUMMY CLOCK PADS FIRST ---
    // Because 180 cols is 4 cols short of a 32-bit chunk (23 words * 8 slices = 184 cols),
    // we send 4 blank dummy slices at the beginning of the row.
    // Inverted Display Rule: 0b1111 represents "all channels dark"
    for (int pad = 0; pad < 4; pad++) {
      uint32_t blank_slice = 0x0F; 
      bit_accumulator |= (blank_slice << (packed_slices * 4));
      packed_slices++;
    }

    // --- STEP B: STREAM YOUR LOGICAL DATA (179 down to 0) ---
    for (int col = 0; col < MATRIX_COLS ; col++) {
      
      uint32_t slice = 0;
      slice |= (text_matrix[0][row][col] & 1) << 0; // Layer 0 -> Pin 3
      slice |= (text_matrix[1][row][col] & 1) << 1; // Layer 1 -> Pin 4
      slice |= (text_matrix[2][row][col] & 1) << 2; // Layer 2 -> Pin 5
      slice |= (text_matrix[3][row][col] & 1) << 3; // Layer 3 -> Pin 6

      // Pixel Inversion (Masked to lowest 4 bits)
      slice = (~slice) & 0x0F;

      bit_accumulator |= (slice << (packed_slices * 4));
      packed_slices++;

      // Every 8 slices (32 bits complete), push straight to hardware
      if (packed_slices == 8) {
        pio_sm_put_blocking(pio, sm, bit_accumulator);
        bit_accumulator = 0;
        packed_slices = 0;
      }
    }

    // NOTE: Because (4 pads + 180 cols) = 184 cols, which is exactly 23 words,
    // packed_slices will ALWAYS equal 0 here. No trailing flush block is required!

    // --- LATCH AND MUTEX DISPLAY REFRESH STEP ---
    // 1. Turn off row drivers to clear the display (Prevents ghosting)
    for (int i = 0; i < MATRIX_ROWS; i++) {
      digitalWriteFast(ROW_PINS[i], LOW);
    }
    delayMicroseconds(1);

    // 2. Pulse Latch pin HIGH to lock data into column drivers
    digitalWriteFast(LATCH_PIN, HIGH);
    delayMicroseconds(1);
    digitalWriteFast(LATCH_PIN, LOW);

  // 3. Switch on current row driver line
    digitalWriteFast(ROW_PINS[row], HIGH);

    delayMicroseconds(2000-brightness);
 // light the display
    digitalWriteFast(ENABLE_PIN, LOW); // display on
    delayMicroseconds(brightness);
    digitalWriteFast(ENABLE_PIN, HIGH); // display off
   }
}


void loop1() {
  scan_and_render_display(led_brightness);
 }
