// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------ //
// output_pulse //
// ------------ //

#define output_pulse_wrap_target 1
#define output_pulse_wrap 5
#define output_pulse_pio_version 0

static const uint16_t output_pulse_program_instructions[] = {
    0xe001, //  0: set    pins, 1
            //     .wrap_target
    0x80a0, //  1: pull   block
    0x6020, //  2: out    x, 32
    0xe000, //  3: set    pins, 0
    0x0044, //  4: jmp    x--, 4
    0xe001, //  5: set    pins, 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program output_pulse_program = {
    .instructions = output_pulse_program_instructions,
    .length = 6,
    .origin = -1,
    .pio_version = output_pulse_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config output_pulse_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + output_pulse_wrap_target, offset + output_pulse_wrap);
    return c;
}
#endif

