
[env:raspberrypi_picow]
platform = raspberrypi
;platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipicow
framework = arduino
board_build.core = earlephilhower

; Append these lines to your active [env:raspberrypi_picow] section:
monitor_speed = 115200
;monitor_port = /dev/ttyACM0 ; linux default
monitor_filters = default
monitor_dtr = 1
monitor_rts = 1


; Define filesystem type and explicit block size allocation
board_build.filesystem = littlefs
board_build.filesystem_size = 1.0m

lib_deps =
    bblanchon/ArduinoJson @ ^7.0.0
    ayushsharma82/ElegantOTA @ ^3.1.0

 ; --- Direct Flash Upload Mapping via Debug Device ---
upload_protocol = cmsis-dap
upload_speed = 5000
debug_tool = cmsis-dap

; Run the conversion script on every build
extra_scripts = post:generate_firmware_bin.py
                post:copy_filesystem_bin.py

build_flags = 
    -DFILESYSTEM=LittleFS
