[env:raspberrypi_picow]
platform = raspberrypi
board = rpipicow
framework = arduino
board_build.core = earlephilhower

monitor_speed = 115200


; Define filesystem type and explicit block size allocation
board_build.filesystem = littlefs
board_build.filesystem_size = 0.5m

lib_deps =
    bblanchon/ArduinoJson @ ^7.0.0

 ; --- Direct Flash Upload Mapping via Debug Device ---
upload_protocol = cmsis-dap
upload_speed = 5000

; === Add these lines to enable wireless deployment updates ===
;upload_protocol = espota
;upload_port = pico4x20led.local

; If you configured a password in Step 2, uncomment and define it here:
; upload_flags = --auth=admin123