#include <Arduino.h>
#include "hardware/pio.h"
#include "hardware/clocks.h"

// Include the compiled PIO header file generated by PlatformIO
#include "pulse_generator.pio.h"

#define ENABLE_PIN 15

// Global hardware trackers
PIO pio_hw = pio0;
uint pio_sm = 0;
uint pio_offset = 0;

// Deterministic blocking trigger function running exclusively on Core 1
inline void __not_in_flash_func(trigger_pulse)() {
    // 1. Force the PIO state machine back to the start index
    pio_sm_exec(pio_hw, pio_sm, pio_encode_jmp(pio_offset));
    
    // 2. Hardware busy-wait: Block CPU until IRQ flag 0 is pulled HIGH by PIO
    // This executes entirely out of Core 1's local RAM cache, avoiding flash memory lag
    while (!(pio_hw->irq & (1u << 0))) {
        __compiler_memory_barrier();
    }
}

// =========================================================================
// CORE 0: Handles Wi-Fi and PIO Allocation
// =========================================================================
void setup() {
    Serial.begin(115200);
    
    if (pio_can_add_program(pio_hw, &pulse_generator_program)) {
        pio_offset = pio_add_program(pio_hw, &pulse_generator_program);
        pio_sm = pio_claim_unused_sm(pio_hw, true);
        pulse_generator_program_init(pio_hw, pio_sm, pio_offset, ENABLE_PIN);
    } else {
        Serial.println("Error: No available PIO instruction space remaining!");
    }
}

void loop() {
    // Wi-Fi routines and non-deterministic background tasks happen here on Core 0.
    delay(1000);
}

// =========================================================================
// CORE 1: Dedicated Trigger Execution (Deterministic & Sync-Blocked)
// =========================================================================
void setup1() {
    delay(500); // Wait for Core 0 to complete allocation
}

void loop1() {
    bool trigger_condition_met = true; // Replace with your hardware criteria

    if (trigger_condition_met) {
        // This function will block and will not return until the 200ns window completes
        trigger_pulse(); 
        
        // At this point, the 200ns pulse sequence has completely finished executing
        // Proceed with immediate, time-sensitive downstream execution logic here
        
        delayMicroseconds(5); // Cooldown to avoid infinite tight re-trigger loops
    }
}
